# Alternative simplified version if release creation fails
# Replace the generate-pdf job with this version:

  generate-pdf:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    
    steps:
    - name: List report directory
      run: ls -l report

    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: report/main.tex
        args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
        extra_system_packages: "py-pygments"
        latexmk_use_xelatex: false
    
    - name: Get current date and commit info
      id: date
      run: |
        echo "date=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT
        echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: "research-paper-${{ steps.date.outputs.date }}-${{ steps.date.outputs.short_sha }}"
        path: "report/*.pdf"
        retention-days: 90
    
    - name: Notify on success
      uses: actions/github-script@v7
      with:
        script: |
          const artifactUrl = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
          
          github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: `📄 PDF generated successfully! [Download from artifacts](${artifactUrl})`
          });
